// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtMzV0ZTFbr-jSFU3awOLN_pitUyjgBPI',
    appId: '1:389864935810:web:f8c4cdbaafe84261133f9b',
    messagingSenderId: '389864935810',
    projectId: 'findseat-42cd4',
    authDomain: 'findseat-42cd4.firebaseapp.com',
    storageBucket: 'findseat-42cd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SOE6iK9hyPsYxNLagk5XY7rwjk3y6vQ',
    appId: '1:389864935810:android:081274716bd09c09133f9b',
    messagingSenderId: '389864935810',
    projectId: 'findseat-42cd4',
    storageBucket: 'findseat-42cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtZ1EYOOMs2U5sMgwRAcLN38mD5z4-58',
    appId: '1:389864935810:ios:140af52a5b77ca76133f9b',
    messagingSenderId: '389864935810',
    projectId: 'findseat-42cd4',
    storageBucket: 'findseat-42cd4.appspot.com',
    iosClientId: '389864935810-18nskb62785fk9jnqq57us8dcd8k5dfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.genielogiciel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMtZ1EYOOMs2U5sMgwRAcLN38mD5z4-58',
    appId: '1:389864935810:ios:140af52a5b77ca76133f9b',
    messagingSenderId: '389864935810',
    projectId: 'findseat-42cd4',
    storageBucket: 'findseat-42cd4.appspot.com',
    iosClientId: '389864935810-18nskb62785fk9jnqq57us8dcd8k5dfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.genielogiciel',
  );
}
